#!/bin/bash
# Refresh nginx real-IP config from Cloudflare's published IP ranges.
# Writes to docker/nginx/cloudflare.conf, which the nginx container mounts
# to /etc/nginx/cloudflare.conf.
# Re-run annually (or after a CF IP range change).
set -euo pipefail

cd "$(dirname "$0")"

OUT=cloudflare.conf
TMP=$(mktemp)

{
  echo "# Generated by cloudflare-refresh.sh on $(date -u +%FT%TZ)"
  for ip in $(curl -fsSL https://www.cloudflare.com/ips-v4); do
    echo "set_real_ip_from $ip;"
  done
  for ip in $(curl -fsSL https://www.cloudflare.com/ips-v6); do
    echo "set_real_ip_from $ip;"
  done
  echo "real_ip_header CF-Connecting-IP;"
} > "$TMP"

mv "$TMP" "$OUT"
echo "[cf-refresh] wrote $(wc -l < "$OUT") lines to $OUT"
